#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestappCenter.Droid.Tests.Resource", IsApplication=true)]

namespace TestappCenter.Droid.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::TestappCenter.Droid.Tests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::TestappCenter.Droid.Tests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::TestappCenter.Droid.Tests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::TestappCenter.Droid.Tests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::TestappCenter.Droid.Tests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::TestappCenter.Droid.Tests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::TestappCenter.Droid.Tests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::TestappCenter.Droid.Tests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::TestappCenter.Droid.Tests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::TestappCenter.Droid.Tests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::TestappCenter.Droid.Tests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::TestappCenter.Droid.Tests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::TestappCenter.Droid.Tests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::TestappCenter.Droid.Tests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::TestappCenter.Droid.Tests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::TestappCenter.Droid.Tests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::TestappCenter.Droid.Tests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::TestappCenter.Droid.Tests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::TestappCenter.Droid.Tests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::TestappCenter.Droid.Tests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::TestappCenter.Droid.Tests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::TestappCenter.Droid.Tests.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int OptionHostName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int OptionPort = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int OptionRemoteServer = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int OptionsButton = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int ResultFullName = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int ResultMessage = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int ResultResultState = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int ResultRunSingleMethodTest = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int ResultStackTrace = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int ResultsFailed = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int ResultsId = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int ResultsIgnored = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ResultsInconclusive = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ResultsMessage = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int ResultsPassed = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ResultsResult = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int RunTestsButton = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int TestSuiteListView = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int appcenter_distribute_dialog_actioned_on_disabled_toast = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int appcenter_distribute_download_progress_number_format = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int appcenter_distribute_downloading_mandatory_update = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int appcenter_distribute_install = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int appcenter_distribute_install_ready_message = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int appcenter_distribute_install_ready_title = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int appcenter_distribute_notification_category = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int appcenter_distribute_unknown_sources_dialog_message = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int appcenter_distribute_unknown_sources_dialog_settings = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int appcenter_distribute_update_dialog_download = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int appcenter_distribute_update_dialog_message_mandatory = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int appcenter_distribute_update_dialog_message_optional = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int appcenter_distribute_update_dialog_postpone = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int appcenter_distribute_update_dialog_title = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int appcenter_distribute_update_dialog_view_release_notes = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int appcenter_distribute_update_failed_dialog_ignore = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int appcenter_distribute_update_failed_dialog_message = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int appcenter_distribute_update_failed_dialog_reinstall = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int appcenter_distribute_update_failed_dialog_title = 2130968594;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
